// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // throw UnsupportedError(
      //   'DefaultFirebaseOptions have not been configured for web - '
      //   'you can reconfigure this by running the FlutterFire CLI again.',
      // );
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATwsBAQKbx69R9hthxZo7owLydtCKLNiw',
    appId: '1:266247700931:android:2cd3d625e019433a0e3d76',
    messagingSenderId: '266247700931',
    projectId: 'doctopia-954fd',
    storageBucket: 'doctopia-954fd.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATwsBAQKbx69R9hthxZo7owLydtCKLNiw',
    appId: '1:266247700931:android:2cd3d625e019433a0e3d76',
    messagingSenderId: '266247700931',
    projectId: 'doctopia-954fd',
    storageBucket: 'doctopia-954fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi0TpkudqaqVpJljibl2WId8rUuijyUGc',
    appId: '1:266247700931:ios:a4b27b820b5dfe420e3d76',
    messagingSenderId: '266247700931',
    projectId: 'doctopia-954fd',
    storageBucket: 'doctopia-954fd.appspot.com',
    iosBundleId: 'drkaz.dev.doctopiaDoctors',
  );
}
